services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: frota
      POSTGRES_USER: admfrota
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - frota-dados:/var/lib/postgresql/data

volumes:
  frota-dados:
